stages:
  - parse-version
  - build
  - deploy
  - validate
  - package-release

include:
  - local: '.gitlab-ci-deploy.yml'
  - local: '.gitlab-ci-helm.yml'
# Additional rules to ensure the chart pipeline runs after the first pipeline
validate-version:
  needs:
    - job: deploy-adservice
      optional: true
    - job: deploy-cartservice
      optional: true
    - job: deploy-checkoutservice
      optional: true
    - job: deploy-currencyservice
      optional: true
    - job: deploy-emailservice
      optional: true
    - job: deploy-frontend
      optional: true
    - job: deploy-paymentservice
      optional: true
    - job: deploy-productcatalogservice
      optional: true
    - job: deploy-recommendationservice
      optional: true
    - job: deploy-shippingservice
      optional: true
    - job: deploy-shoppingassistantservice
      optional: true

package-release-chart:
  needs:
    - job: validate-version