# This is a Kubernetes Secret
apiVersion: v1
kind: Secret
metadata:
  name: private-gke-repo # The name of the Secret
  namespace: argocd # The namespace where the Secret is deployed
  labels:
    argocd.argoproj.io/secret-type: repository # A label indicating that this Secret is used for a repository
stringData:
  url: https://gitlab.com/Hamdane10/gke-cloud-project.git # The URL of the Git repository
  password: "glpat-3EptXchc8yxyTYRa3xxJ" # The password (or token) for the Git repository
  username: "Hamdane10" # The username for the Git repository