---
- name: Deploy Load Generator Container
  hosts: load_generator
  become: true

  tasks:
    - name: Copy docker-compose file
      copy:
        src: ../scripts/docker-compose.yml
        dest: /tmp/docker-compose.yml
        mode: '0644'

    - name: Get frontend IP address
      command: kubectl get service frontend-external -n {{ kubernetes_namespace }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: frontend_ip
      delegate_to: localhost
      changed_when: false
      become: false

    - name: Run docker compose
      shell: |
        cd /tmp && \
        FRONTEND_ADDR_IP={{ frontend_ip.stdout }}:80 docker compose up -d
      args:
        executable: /bin/bash
    
    # Command to swarm the load generator from inside the container
    # curl "http://localhost:8089/swarm" -X POST -H "Content-Type: application/x-www-form-urlencoded" --data "user_count=10&spawn_rate=1&host=http://34.65.74.161:80"
    - name: Swarm the load generator
      uri:
        url: "http://localhost:8089/swarm"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body: "user_count=10&spawn_rate=1&host=http://{{ frontend_ip.stdout }}:80"
        status_code: 200